FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
    && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub

RUN apt update && \
    apt install -y \
    vim zsh git ssh sudo curl language-pack-en tmux
RUN update-locale LANG=en_US.UTF-8

RUN ln -s /opt/conda/bin/python /usr/bin/python
