FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel


# ENVIRONENT VARIABLES
# todo,\で繋げたらユーザー作成でエラー．
ENV UID 19094
ENV USER_NAME yoshimura.19094
ENV CUDA cu113
ENV TORCH 1.10.0


# apt-get update や apt-get upgrade の前に. 参考:https://zenn.dev/takakurasato/scraps/d3e0ee6132a5c5
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
    && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub


# install essential softwares
RUN apt update && \
    apt install -y \
    vim zsh git ssh sudo curl language-pack-en tmux
RUN update-locale LANG=en_US.UTF-8

# install mecab install
RUN apt install -y \
    mecab libmecab-dev mecab-ipadic-utf8 xz-utils file

# python 3.7.11
# link to python
RUN ln -s /opt/conda/bin/python /usr/bin/python

# python -m pip install packages
RUN python -m pip install --upgrade pip
RUN python -m pip install \
    numpy matplotlib scikit-learn pandas gensim mojimoji pyknp \
    tensorboard nltk seqeval
    # pylint tqdm sentencepiece transformers scikit-learn spacy==2.3.7 scispacy black seaborn

# install optuna
RUN apt install -y libssl-dev python3-dev libmysqlclient-dev sqlite3 && \
    python -m pip install optuna mysqlclient scikit-optimize


# user settings
RUN adduser --uid ${UID} --force-badname --shell /bin/bash --disabled-password --no-create-home ${USER_NAME}
RUN mkdir -p /home/${USER_NAME}/projects/project
RUN echo ${USER_NAME}:${USER_NAME} | chpasswd
RUN ln -s /workspace /home/${USER_NAME}/projects/project

# ownership
RUN chown -R ${USER_NAME}:${USER_NAME} /home/${USER_NAME}
RUN chmod 755 /home/${USER_NAME}
# RUN chown ${USER_NAME}:${USER_NAME} /workspace
# RUN chmod 755 /workspace

# sudo settings
RUN usermod -aG sudo ${USER_NAME}
RUN echo "root:passwd" | chpasswd && echo "${USER_NAME}:passwd" | chpasswd

# github settings
RUN git config --global user.email umeboshia@gmail.com
RUN git config --global user.name umeboshia
RUN mkdir /home/${USER_NAME}/.ssh

USER ${USER_NAME}




