FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel

# apt-get update や apt-get upgrade の前に. 参考:https://zenn.dev/takakurasato/scraps/d3e0ee6132a5c5
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub

# install essential softwares
RUN apt update && apt install -y vim zsh git ssh sudo language-pack-en tmux
RUN update-locale LANG=en_US.UTF-8


# python 3.7.11

# link to python
# デフォルトは/opt/conda/bin/python．ユーザーを作ると追加
# RUN ln -s /opt/conda/bin/python /usr/bin/python

# python -m pip install packages
RUN python -m pip install --upgrade pip
RUN python -m pip install numpy matplotlib pylint tqdm sentencepiece transformers scikit-learn tensorboard spacy==2.3.7 scispacy black seaborn

